### PR TITLE
New Example Module Chat with Socket.io

### PR DESCRIPTION
**Pull request by movibe**
* Bower: angular-socket-io
* Directive autofocus
* Include server/server.js socket.io

### CODE REVIEW

**Comment by beeman** [comment]
I've enhanced it a little as you can see in [this commit](https://github.com/beeman/loopback-angular-admin/tree/movibe-module-chat).

It would be good if we have a list/number of active users, and a message when a user enters the room.

In the future private messaging and notifications would be awesome too, but it looks like those are not the most easy things to do.

**Comment by movibe** [comment]
Thanks @beeman !
It was their great improvements, we will list some resources for me to help assemble.

I have other side projects, but this has been my favorite because while I'm contributing, I am learning a lot.

As for the chat features, can do.

1) Create a database to store the messages
2) List the users who are online
3) Create chat rooms between online or offline
4) Notification unread messages

Think about changing the shape of socket.io, for when data is entered in the database, not as put on the server, in fact I got another example to see how it looked and I was glad you likes.

**Comment by beeman** [comment]
A while back i've found [this project](https://github.com/tamaspiros/AngularChat), it has some nice features built in, it might be worth looking at too :)

**Comment by macbroadcast** [comment]
yes, i found that one too, a working example is here http://onechat.herokuapp.com ;)

**Comment by beeman** [comment]
@macbroadcast that one looks nice too. Do you know if the source is available?

**Comment by pulkitsinghal** [comment]
Seems like the build failed for a rather simple reason:
```
Running "loopback_sdk_angular:production" (loopback_sdk_angular) task
Warning: Cannot load LoopBack app server/server.js Use --force to continue.
```

**Comment by beeman** [comment]
I've decided to postpone the socket.io integration. I think it does not add enought value to the project at this moment. 

If someone needs it integrated it can check this PR, I'll mention it in the README. :)

**Pull request closed without merging**
