### PR TITLE
Languages and Menu

### PR DESCRIPTION
**Pull request by movibe**
* English
* Dutch
* German

### CODE REVIEW

**Comment by beeman** [comment]
Thanks!

What tool or procedure do you use for making the translations (.po files)? Is it possible to write down you steps? Than I'll update the README.md accordingly!

**Comment by macbroadcast** [comment]
I would like to help transating to german ;)

**Comment by beeman** [comment]
@macbroadcast that would be great! 

I made the Dutch translation using [this site](https://translate.zanata.org/zanata/iteration/view/loopback-angular-admin/1), maybe you can join in here.

**Comment by macbroadcast** [comment]
@beeman Sure , guess you need to authorize me , because i can´t type in the fields ;)

P.S. Still interested in your question what tools @movibe use to generate the .po files

**Comment by beeman** [comment]
@macbroadcast you should have permission now :)

**Comment by macbroadcast** [comment]
Done !

**Comment by movibe** [comment]
I am using http://poedit.net/ for Mac, is very simple.

To create a new translation use the po/template.po file
Or edit using the language.po file

**Comment by beeman** [comment]
@macbroadcast thanks a lot for the translation! I've just added it to the project!

@movibe thanks for the info! If you like I can add you to the translation site too, to manage translations in a central place :)

**Comment by movibe** [comment]
@beeman  Please add me, I tried to translate but there was not as administrator was unable

**Comment by beeman** [comment]
@movibe I've added you as a maintainer!

**Comment by movibe** [comment]
Thanks

**Comment by macbroadcast** [comment]
My pleasure @beeman , a question regarding language support,because i see your using gettext, is´nt https://docs.angularjs.org/guide/i18n  the "official" method for multilingual support ? :)

**Comment by beeman** [comment]
@macbroadcast the support for angular-gettext was added by @movibe , I didn't make the initial decision but I fully agree with it!

I see angular-gettext as a more complete way to do the translations, for instance with the grunt tasks to extract the translated strings, and the 'official' method seems more low-level.

Of course i'm always open to look at alternatives :)

**Pull request merged**
