### PR TITLE
Gulp version

### PR DESCRIPTION
**Pull request by movibe**
New Gulp Version

### CODE REVIEW

**Comment by beeman** [comment]
Hi @movibe , thanks for this PR.

I have looked at it but I am afraid it changed too much for my liking. For instance the move from `client` to `public` is not something I like to see.

All in all it is too big to merge right away. I am sorry for the effort you put into it.  

For in the future it will be better to open an issue to discuss how to implement this.

**Comment by theorye** [comment]
It would make a good fork for someone who wants a GULP version :D

**Comment by movibe** [comment]
Hello @beeman , actually I'm changing all the original concept in the way the project is currently, according to some experiences in work I have done with AngularJS.

I think we can always improve a job that is already at an optimum level, but I think from now on we are moving on different paths.

Despite having made the suggestion to use the version Gulp instead of Grunt, which becomes much easier to understand and separation of duties responsibilities, you wished to continue the Grunt and I decided to continue the evolution of Gulp version only this change has become difficult to merge the two projects.

Some issues such as file structure and standards of the codes are not well defined and I really want to fix it, and make several improvements in the way the project is today.

So I'm unlinking my changes and making a Gulp version of the project, which will continue without merge requests.

I hope that my efforts will inspire other contributors participate in our projects.

I am very grateful that you have started this project that helped me and I hope that in the future we can get in a concession to join forces again.

A big hug

**Comment by beeman** [comment]
@movibe thanks a lot for your help on the project so far and I wish you good luck with your fork. 

This project will most probably switch to gulp somewhere in the future, it's just not the right time for me to do it now. I understand you want to move on :)

Grande abraço!

**Pull request closed without merging**
