### PR TITLE
Added role management and acl

### PR DESCRIPTION
**Pull request by shalkam**
Taken care of those 2 points on the todo list :
- Map API roles to Narzerus/angular-permission
- Permissions on user actions (non-admins cannot access advanced functions)

also I added a module for roles management and select list for user/role attachment on the user edit page.

There a bunch of issues that needs to be taken care of like:
- when checking if user role exists using the api using this url HEAD /users/{id}/roles/rel/{fk}
  it sends a 404 error when it doesn't exist so I had to comment out those lines here https://github.com/shalkam/loopback-angular-admin/blob/master/client/app/modules/users/config/users.auth.js#L28
- the way the user roles are attached in the user boot file : https://github.com/beeman/loopback-angular-admin/blob/master/server/boot/02-load-users.js
  doesn't add new rolemapping into the database which is necessary to determine the user role.
  When I do a GET /roleMappings I get an empty array.
- I don't know how to use angular-toasty in routes when using angular permission
- may be there other issues too

### CODE REVIEW

**Comment by beeman** [comment]
@shalkam First of all thanks a lot for your contribution! It's really appreciated and I think this is functionality that a lot of people welcome in this project, myself included!

One of the things that I notice in the PR is that a lot of changes in the files are just changes in whitespace. Can you please make sure that the lines you are committing are only actual changes? This makes it way easier for me to review this.

There is a `.editorconfig` file in the root of the project that specified 2 spaces for indents, it would be great if you can adhere to this rule.

If the whitespace is fixed I'm happy to review this an polish it so it will fit in the system.

Again, thanks for contributing!

**Comment by shalkam** [comment]
@beeman thanks for pointing out the existence of the _.editorconfig _  I've installed the editor config plugin for my code editor and it should be fixed now.

I've taken a look at the files changed it seems to be showing all the related files, with the exception of some file at the end where square brackets have been changed into curly brackets I don't know why this happened.

**Comment by beeman** [comment]
@shalkam Thanks a lot for fixing the indents.

the reason that the model files had a change in the `methods` key from arrays (square brackets) to objects (curly braces) is probably because you ran `slc loopback:model` to generate the `roleMapping` model?

I've updated the master branch with this change so it should not appear in your PR again.

**Comment by shalkam** [comment]
> because you ran slc loopback:model to generate the roleMapping model?

Yes that is exactly what happened

**Comment by beeman** [comment]
Hey @shalkam, I finally found some time to test this commit. 

The first thing I found is that I can't get it running when I do a `git clone`, `npm install` (which triggers `bower install`) and `grunt serve`.

I get this error message in my browser console:

```
angular-permission.js:210 Uncaught TypeError: angular.module(...).decorator is not a function
angular.js:4149 Uncaught Error: [$injector:unpr] Unknown provider: TransitionPropertiesProvider <- TransitionProperties
http://errors.angularjs.org/1.3.12/$injector/unpr?p0=TransitionPropertiesProvider%20%3C-%20TransitionProperties
```

I didn't check really deep into it, but it looks like some issue with angular-permission.

Speaking of angular-permission, I have second thoughts on using this library in the front end of the app. As you noted in your comment here https://github.com/beeman/loopback-angular-admin/pull/176/files#diff-1ed3f3562d8ab3a77ce7f8ab947e538dR3 , there is an overlap in the name Role. Additionally, I don't think it adds too much value. I have created a custom `AclService` at work that does the basic checks, combined with a method on the API that gives a summary of the logged in users permissions. I will have a look to see if I can port those methods to this project. 

I've fixed the merge issues and adjusted a small thing in bower.json and pushed it up to this branch https://github.com/beeman/loopback-angular-admin/tree/shalkam-master . Let's continue in that branch for now.

**Comment by beeman** [comment]
FYI, I've just added the method for getting user information, this can be resolved when the app loads, in order to have a mapping of the roles

https://github.com/beeman/loopback-angular-admin/commit/ad84712bccaec304cce65adc69229eb0c71e8e7d

**Comment by shalkam** [comment]
@beeman Hi, Sorry for the delay ... couldn't get back to you sooner.
I've installed the files from my repository and I saw that it shows the same error you reported I take care of it and get back to you

**Comment by beeman** [comment]
@shalkam Thanks for your response!

Please not that I have started working on a major update in the [develop branch](https://github.com/beeman/loopback-angular-admin/tree/develop). It completely changes the front end so it might be better to develop against that branch.

**Comment by shalkam** [comment]
@beeman I've got project being developed using the master branch I will finish this one then I will be more than glad to contribute to the develop branch. 
I think later on the ng-admin project https://github.com/marmelab/ng-admin should be used as reference and add advanced functions like menu management.

**Comment by beeman** [comment]
@shalkam thanks a lot for submitting a PR. 

I'm closing this PR as I will be pushing out an updated `develop` branch soon that has ACL's and roles and permissions enabled.

**Pull request closed without merging**
