### PR TITLE
AngularJS Refactored for Modular Development

### PR DESCRIPTION
**Pull request by movibe**
Version Refactored for Development Modular Method in AngularJS

### CODE REVIEW

**Comment by beeman** [comment]
I have checked out the commit and I'm really impressed with the work you did! Thanks a lot!!

There are a couple small things i'd like to see changed or discus before I merge the PR.

In random order:

- Add the folder .strong-pm/ to .gitignore and remove from the repo 
- Add the file providers.json to .gitignore and remove from the repo (it is now committed with your Google AppID+Secret)
- Authenticating using one of the passport providers gives me and error message: 'Error: No default engine was specified and no extension was provided.' 
- I think there is an overlap between the Sandbox and the Components module you added. I'd like the Sandbox to be a playground and demonstration area of the included features and plugins and I think the Autofields component should be just one of them. Not sure if you had other intentions with the Components menu.

For now that's it! Works like a charm this way and it really looks like it's easily extended! I will check to see if there is a way to dynamically include the modules in the index.html file, to make it even more flexible!

The angular-gettext part looks nice too, I'll translate it to Dutch when it's merged :) 

Thanks again for all your work on this project! :)

**Comment by beeman** [comment]
Thanks a lot! I've merged all your changes! :)

**Comment by movibe** [comment]
Thanks, I made the changes you recommended me.

I deleted the module components and did merge with the content in your sandbox module.

It would be nice even a form of self add modules in the index.html file automatic way, I tried something with Grunt, but not found.

**Comment by beeman** [comment]
It looks like my [last commit](f6178dc91012c0e586294f3bdb04d6bd09d0464a) fixes that, found it in [this commit](3d0c90c67b661147e7934b30639172b214b213ac) by @manuelnaranjo :)

**Pull request merged**
