### PR TITLE
Beeman gulp

### PR DESCRIPTION
**Pull request by movibe**
* Removed Grunt 
* Added Gulp
* Add Angular Cache and Gulp Task Templates
* Add AdminLTE Less and Gulp Task Less
* Gulp Build

### CODE REVIEW

**Comment by sajjad-ser** [comment]
+1 please use  gulp

**Comment by movibe** [comment]
I need help to fix for wercker integration. @beeman can you help me?

**Comment by beeman** [comment]
Of course @movibe , I'll check this pull request in the next couple of days!

**Comment by beeman** [comment]
I finally took the time to look at this PR, excuse me that it took so long!

The gulp part looks fine for the most part but I think it still needs some work. What I notice is that of all the js and css files that are hardcoded in index.html again. As this list keeps on growing that needs to be automated. 

More importantly I am still not sure about keeping this layout and thus building it in around less is not something I'd like to do right now. At this moment I look at using [this theme](http://start-angular.github.io/sb-admin-angular/preview) and will start testing it when I can install it using bower.

My conclusion for now is that it would be better to implement gulp once the layout is finished, and then look how gulp can aid in customizing that layout.

**Comment by movibe** [comment]
Hi @beeman , thanks for looking my PR.

I will await your new layout, I have a more complete version of Gulp, and I'm to implement this new version as a suggestion to replace the Grunt.

**Comment by beeman** [comment]
Thanks a lot for understanding and your help on the project @movibe !

**Pull request closed without merging**
