### PR TITLE
Language features

### PR DESCRIPTION
**Pull request by movibe**
* New Header Menu Lang
* Rotoscope selectLang
* Show only available Lang

### CODE REVIEW

**Comment by beeman** [comment]
Thanks a lot! Did you read my question on the last commit? :)

**Comment by movibe** [comment]
I saw now, but I answered

**Comment by beeman** [comment]
Thanks a lot! Wil try to merge both  of your PR's later today!

**Comment by movibe** [comment]
Thanks @beeman! I managed to run the login via providers, but think it needs some finishing touches, if you can take a test and analyzed will be very interesting

**Pull request merged**
