### PR TITLE
bootstrap seed data with findOrCreate()

### PR DESCRIPTION
**Pull request by pulkitsinghal**
...  also added the default flavor of logging used by loopback boot scripts which can be enabled by setting an env variable before any existing launch command:
`DEBUG=boot:* npm start`
`DEBUG=boot:* npm run dev`

### CODE REVIEW

**Comment by pulkitsinghal** [comment]
@beeman - what do you think, is this PR merge worthy?

**Comment by beeman** [comment]
@pulkitsinghal the quality of the code is perfectly fine, I'm just not sure why one would like to use `findOrCreate` for loading the initial/volatile data?

The debugging is something that is more than welcome!

**Comment by beeman** [comment]
After looking at it I decided to merge it :)

The creation of the data will change anyway, once it's done well in https://github.com/beeman/loopback-advanced-models

**Comment by pulkitsinghal** [comment]
@beeman - Thank you for accepting it but I still owe you an explanation!

> I'm just not sure why one would like to use findOrCreate for loading the initial/volatile data?

I had turned on file-level saves (db.json) in the memory connector, in order to understand the inner workings of the relationships and data a bit better. At which point I found categories and products piling up and it just felt like I could make it cleaner. Perhaps it is a meaningless optimization as the right thing to do is to remove the boot script after "seeding" the data. But you know, I just like idempotency so much that I couldn't leave it alone :(

**Comment by pulkitsinghal** [comment]
@beeman - would you like me to submit another PR that updates the README as well with info about enabling logs?

```
DEBUG=boot:* npm start
DEBUG=boot:* npm run dev
```

**Pull request merged**
